# This workflow will build and test a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CONTRIBUTORS.txt'
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-macos:
    name: macOS build and test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  build-linux:
    name: Linux build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swift-quic/setup-swift@main
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
